version: '3.7'
services:
  prometheus:
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: 'grafana/grafana:8.5.4'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=test
      - GF_SECURITY_ADMIN_PASSWORD=1234
    depends_on:
      - prometheus
    restart: always